### ISSUE TITLE
brew fails for old version Python 3.5

### ISSUE THREAD

**Issue by rnestler** [sashkab/homebrew-python#126]
I have installed Python 3.5 using this formula, but after updating brew gave me an error when running `brew list sashkab/python/python@3.5` to check if it is installed:
```
bash-3.2$ brew list  sashkab/python/python@3.5
Error: No available formula with the name "sashkab/python/python@3.5".
```

Also `brew info` gives me a similar error:
```
bash-3.2$ brew info sashkab/python/python@3.5
Error: No available formula or cask with the name "sashkab/python/python@3.5".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

We use automated scripts (Ansible) to maintain our CI runners and we need Python 3.5 for legacy reasons. Is there a way to keep supporting Python 3.5?

**Comment by sashkab** [comment]
HI @rnestler, 

Python 3.5 reached [end of life status with the release of Python 3.5.10](https://www.python.org/downloads/release/python-3510/). I decided to support here only currently supported versions of Python. Feel free to fork this repository and restore `python@3.5.rb` from 99c31695507e3b73f3586454457205677cd01a99. Furthermore, main homebrew currently supports Python 3.7, 3.8 and 3.9 so with EOL of Python 3.6 in December 2021, I don't think I will need to maintain this tap any longer.

Thanks.
