### ISSUE TITLE
failing on Big Sur Mac Book Pro M1 2020

### ISSUE THREAD

**Issue by awadhesh-tanwar** [sashkab/homebrew-python#137]
==> Downloading https://pypi.org/packages/source/s/setuptools/setuptools-58.0.3.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/6d/f2/85d487d516e7319fad8052a6bb4a4447244e59f830d17515fb40d3141072/setuptools-58.0.3.tar.gz
######################################################################## 100.0%
==> Downloading https://www.pypi.org/packages/source/p/pip/pip-21.2.4.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/52/e1/06c018197d8151383f66ebf6979d951995cf495629fc54149491f5d157d0/pip-21.2.4.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.org/packages/source/w/wheel/wheel-0.37.0.tar.gz
==> Downloading from https://files.pythonhosted.org/packages/4e/be/8139f127b4db2f79c8b117c80af56a3078cc4824b5b94250c7f81a70e03b/wheel-0.37.0.tar.gz
######################################################################## 100.0%
==> Downloading https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tar.xz
######################################################################## 100.0%
==> Installing python@3.6 from sashkab/python
==> ./configure --prefix=/opt/homebrew/Cellar/python@3.6/3.6.15 --enable-ipv6 --datarootdir=/opt/homebrew/Cellar/python@3.6/3.6.15/share --datadir=/opt/homebr
Last 15 lines from /Users/awadhesh.tanwar/Library/Logs/Homebrew/python@3.6/01.configure:
checking size of float... 4
checking size of double... 8
checking size of fpos_t... 8
checking size of size_t... 8
checking size of pid_t... 4
checking size of uintptr_t... 8
checking for long double support... yes
checking size of long double... 8
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
configure: error: Unexpected output of 'arch' on OSX

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sashkab/homebrew-python/issues

**Comment by sashkab** [comment]
I don't think 3.6.x is supported on M1... You probably want to use 3.8.x or newer. 

[source](https://stackoverflow.com/questions/65653464/installation-of-earlier-versions-of-python-prior-to-3-8-fails-on-mac-with-m1-c)

Also, 3.6 is reaching EOL soon, so I will drop supporting it anyway.

**Comment by sashkab** [comment]
From upstream issue: [gh-41100](https://bugs.python.org/issue41100#msg382939)

> The plan is to also support 3.8 on Big Sur and Apple Silicon as 3.8 is still in bugfix mode.  There are no plans to backport support to 3.7 and 3.6 which are in the security-fix-only phase of their release cycles.
