### ISSUE TITLE
Request 3.6 return to the repository.

### ISSUE THREAD

**Issue by BPV123** [sashkab/homebrew-python#142]
Hello,

Requesting 3.6 return to the repository, I know its reached end of life, but 3.6 is currently the only working version for OBS studio. 

Thank you so much.

Benjamin

**Comment by sashkab** [comment]
Why don't you ask OBS studio to support modern versions of Python?

**Comment by BPV123** [comment]
If only. The Python Script User community of OBS Studio, is very small in comparison to general user pool. I can ask all day. But the reality is that OBS is Open source , and they get to what the user community needs most. OBS Studio on Mac is relatively new. Home brew is a fantastic tool. And this formula makes the installation and utilization of Python a breeze. For ease of use, as the OBS Studio Mac side grows, I figured I'd open this line of communication. 

Thank you for responding so quickly. 

Benjamin
