### ISSUE TITLE
Would be good to have bottles

### ISSUE THREAD

**Issue by BrendanSimon** [sashkab/homebrew-python#27]
Would be good to have bottles, for quicker installs and also know the exact binaries people have installed.
Is that possible or just too hard?

**Comment by sashkab** [comment]
Hi, thanks for suggestion. I agree, but I don't have a space to host bottles.

**Comment by desertkun** [comment]
AFAIK you can upload them to [bintray](https://bintray.com/account/pricing?tab=account&type=pricing) (For Open Source Plan).

**Comment by sashkab** [comment]
Thanks for the link @desertkun. I'll research this.

**Comment by sashkab** [comment]
I don't think I will be doing anything here. Due to removal of i386 SDK in latest version of command line tools, there is no way to support universal binaries on macOS 10.13+. I've deprecated this project.

**Comment by BrendanSimon** [comment]
That's a shame :(
I don't use this project for i386 builds.  I use this project to get the various versions of python (e.g 2.7, 3.5, 3.6, 3.7) and keep them up to date (instead of the latest 2.x or 3.x which homebrew does by default)

**Comment by desertkun** [comment]
Same, could you please at lease support x64?

**Comment by sashkab** [comment]
@BrendanSimon @desertkun — didn't know someone was using this for something other than universal binaries. Wondering why you decided to use this, while there is better solution — [pyenv](https://github.com/pyenv/pyenv)?

**Comment by desertkun** [comment]
AFAIK, `pyenv` doesn't do binaries, which is the whole purpose of this issue. I, in the other hand, just want to have a quick install instead.

**Comment by sashkab** [comment]
homebrew/homebrew-core@8e335a1146e31a43fef7ce2deb56aeab8f0d612d

**Comment by sashkab** [comment]
Reopening, to implement at some time in a future.

**Comment by sashkab** [comment]
Depends on #34.
