### ISSUE TITLE
Would be good to install PythonXYZ

### ISSUE THREAD

**Issue by BrendanSimon** [sashkab/homebrew-python#28]
Would be good to install PythonXYZ, so that if I really need to use Python-3.6.5 for one project and Python-3.6.6 for another, than I can.

Is that possible or just too hard?

**Comment by sashkab** [comment]
I follow same logic as Homebrew project: support only latest version of the package. 

If you need to have multiple versions, you might want to use [pyenv][0].

[0]:https://github.com/pyenv/pyenv
