### ISSUE TITLE
Support for Py 3.6.8

### ISSUE THREAD

**Issue by tispratik** [sashkab/homebrew-python#78]
Thank you for the wonderful repo for easy installation of Python. May i ask if there is a way you can provide 3.6.8 as well? Not sure how difficult it is.

**Comment by sashkab** [comment]
I track latest version of each Python. You can try extract an old commit where 3.6.8 was version in python@3.6. Or fork the project and update to 3.6.8. I won't do it sorry.

**Comment by tispratik** [comment]
Thanks @sashkab, I did the fork and updated the version. It works well. Shall i provide a PR?

**Comment by sashkab** [comment]
Probably not. Thanks!
