### ISSUE TITLE
how does one get this to bind to `python3`?

### ISSUE THREAD

**Issue by Pomax** [sashkab/homebrew-python#87]
I would be good to add a bit to the README.md that explains how to make `python3` etc use a version installed this way.

**Comment by sashkab** [comment]
When you install a package, you get instructions how to use it. See for example https://github.com/sashkab/homebrew-python/blob/master/Formula/python%403.7.rb#L279

**Comment by sashkab** [comment]
Should you want to update README -- I'll accept the pull request.
